name: build to DockerHub
on:
    push:
        branches:
            - "develop/*"
            - "main"
    pull_request:
        types:
            - "opened"
jobs:
    build_and_push:
        runs-on: ubuntu-latest
        steps:
            # リポジトリを仮想マシンにチェックアウト
            - name: Checkout the repo
              uses: actions/checkout@v3

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  # リポジトリシークレットにDockerHubのクレデンシャルを登録する
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}

            # Dockerのメタデータを取得
            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: koh124/cicd

            # イメージをビルドしDockerHubにpush
            - name: Build and Push Docker image
              uses: docker/build-push-action@v2
              with:
                  # relative path from repo root to Dockerfile
                  context: .

                  #  push to DockerHub repo
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
